// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BulkIssue.Models;

public partial class Test
{
    public Guid Id { get; set; }

    public string Value { get; set; }

    [Timestamp]
    public byte[] RowVersion { get; set; }
}